export const GET_DEVICES_REQUESTED = 'GET_DEVICES_REQUESTED';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAILED = 'GET_DEVICES_FAILED';

export const DELETE_DEVICE_REQUESTED = 'DELETE_DEVICES_REQUESTED';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICES_SUCCESS';
export const DELETE_DEVICE_FAILED = 'DELETE_DEVICES_FAILED';

export const CREATE_DEVICE_REQUESTED = 'CREATE_DEVICES_REQUESTED';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICES_SUCCESS';
export const CREATE_DEVICE_FAILED = 'CREATE_DEVICES_FAILED';

export const FIND_DEVICE = 'FIND_DEVICES';
export const FIND_DEVICE_SUCCESS = 'FIND_DEVICES_SUCCESS';
export const FIND_DEVICE_FAILED = 'FIND_DEVICES_FAILED';

export const UPDATA_DEVICE_REQUESTED = 'UPDATA_DEVICES_REQUESTED';
export const UPDATA_DEVICE_SUCCESS = 'UPDATA_DEVICES_SUCCESS';
export const UPDATA_DEVICE_FAILED = 'UPDATA_DEVICES_FAILED';
