export const GET_DEVICES_REQUESTED = 'GET_DEVICES_REQUESTED';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAILED = 'GET_DEVICES_FAILED';

export const DELETE_DEVICES_REQUESTED = 'DELETE_DEVICES_REQUESTED';
export const DELETE_DEVICES_SUCCESS = 'DELETE_DEVICES_SUCCESS';
export const DELETE_DEVICES_FAILED = 'DELETE_DEVICES_FAILED';

export const CREATE_DEVICES_REQUESTED = 'CREATE_DEVICES_REQUESTED';
export const CREATE_DEVICES_SUCCESS = 'CREATE_DEVICES_SUCCESS';
export const CREATE_DEVICES_FAILED = 'CREATE_DEVICES_FAILED';

export const FIND_DEVICES_REQUESTED = 'FIND_DEVICES_REQUESTED';
export const FIND_DEVICES_SUCCESS = 'FIND_DEVICES_SUCCESS';
export const FIND_DEVICES_FAILED = 'FIND_DEVICES_FAILED';

export const UPDATA_DEVICES_REQUESTED = 'UPDATA_DEVICES_REQUESTED';
export const UPDATA_DEVICES_SUCCESS = 'UPDATA_DEVICES_SUCCESS';
export const UPDATA_DEVICES_FAILED = 'UPDATA_DEVICES_FAILED';
