export const GET_DEVICES_REQUESTED = 'GET_DEVICES_REQUESTED';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const GET_DEVICES_FAILED = 'GET_DEVICES_FAILED';

export const DELETE_DEVICE_REQUESTED = 'DELETE_DEVICE_REQUESTED';
export const DELETE_DEVICE_SUCCESS = 'DELETE_DEVICE_SUCCESS';
export const DELETE_DEVICE_FAILED = 'DELETE_DEVICE_FAILED';

export const CREATE_DEVICE_REQUESTED = 'CREATE_DEVICE_REQUESTED';
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_FAILED = 'CREATE_DEVICE_FAILED';

export const FIND_DEVICE = 'FIND_DEVICE';
export const FIND_DEVICE_SUCCESS = 'FIND_DEVICE_SUCCESS';
export const FIND_DEVICE_FAILED = 'FIND_DEVICE_FAILED';

export const UPDATA_DEVICE_REQUESTED = 'UPDATA_DEVICE_REQUESTED';
export const UPDATA_DEVICE_SUCCESS = 'UPDATA_DEVICE_SUCCESS';
export const UPDATA_DEVICE_FAILED = 'UPDATA_DEVICE_FAILED';
